### PR TITLE
date.timezone, fix https://github.com/PocketMine/PocketMine-MP/issues…

### PR DESCRIPTION
**Pull request by thebigsmileXD**
…/4058

### CODE REVIEW

**Comment by PEMapModder** [comment]
Don't hardcode the time!

**Comment by thebigsmileXD** [comment]
I was told to do so by Intyre.

**Comment by Intyre** [comment]
@PEMapModder happy? 3d306dd

**Comment by thebigsmileXD** [comment]
@Intyre will the actual timezone really be set? Because i don't think it will be generated on startup, will it?

**Comment by Intyre** [comment]
I don't have, want or use Windows. You have to check that for yourself. Details [here](https://github.com/PocketMine/PocketMine-MP/issues/4058#issuecomment-194881894).

**Comment by thedeibo** [comment]
image
Hmm, its always been like this for me.

**Comment by PEMapModder** [comment]
@thedeibo debug on?

**Comment by thedeibo** [comment]
debug:
 #To enable assertion execution, set zend.assertions in your php.ini to 1
 #If > 1, it will show debug messages in the console
 level: 1

**Comment by thebigsmileXD** [comment]
@thedeibo Debug level 2. If there won't be any "You are requered to set the date-timezone" issues popping up, it works. May you show us the php.ini?

**Comment by thedeibo** [comment]
image
php.ini ---> http://paste.ubuntu.com/15391106/

**Comment by thebigsmileXD** [comment]
Is that a clean install?

**Comment by thedeibo** [comment]
clean.

**Comment by thebigsmileXD** [comment]
@thedeibo but: Have you used the latest library? ;)

Also, you get this errors after some minutes, not instantly.
For me it appeared randomly between 5 and 15 minutes. Had you let it run for so long? Whats your system timezone?

**Comment by thedeibo** [comment]
ive tried leaving it on for 30 mins, same resault. My timezone ( as corrected by a wise person ) is Europe/London.

**Comment by thebigsmileXD** [comment]
Ah xD
London is gmt+0.
Can you just for testing try another timezone?

**Comment by thedeibo** [comment]
Ok, I added a completly different timezone to the php.ini. 
(

> ;Custom PocketMine php.ini file
> zend.enable_gc = On
> max_execution_time = 0
> date.timezone = America/New_York
> memory_limit = 256M
> error_reporting = -1
> display_errors = stderr
> display_startup_errors = On

Ive got this. 
> [05:53:41] [Server thread/INFO]: Loading pocketmine.yml...
> [05:53:41] [Server thread/INFO]: Loading server properties...
> [05:53:41] [Server thread/INFO]: Selected English (eng) as the base language
> [05:53:41] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.0.0 alpha
> [05:53:41] [Server thread/INFO]: Opening server on 0.0.0.0:19132


I also tried the difference between 
date.timezone = Europe/London 
and deleting that line. I see no difference. 

Ive done my own experiment ( risked wrecking my laptop time )  and the server uses the laptop's time anyway. So, as long as the PC's time is correct, and not bugged out, then it should work. 
Sometimes, it could be a problem with times colliding, and that does tend to cause problems.
(most of you would know that xD )

**Comment by thedeibo** [comment]
But, if you think about it, If they is an official installer, and the php.ini had "date.timezone = Europe/London " in it, then it would be a problem, so in my head, the "date.timezone" part actually did not exist in the first place.
Reason: It actually doesn't exist. 
Ive looked at a very old Official WIndows installer, and it did not include date.timezone in the php.ini, and i understand why. 
Think about it, it makes sense. :) 
(if I sound at all wrong, rude, or annoying, tell me. :P , its just me attempting to give all the info I know)

**Comment by thebigsmileXD** [comment]
@thedeibo Incorrect. Windows tried to add the value, but never did. Now it should atleast add it. Do you know the issue i made? Doesn't seems so, else you would know why i even mentioned this here.

**Comment by thedeibo** [comment]
THe issue is known, Im just explaining, and as for the windows adding values, ehh.... idk

**Pull request closed without merging**
